### ISSUE TITLE
Paper link is wrong for GAN-based anomaly detection: A review

### ISSUE THREAD

**Issue by forestm** [bitzhangcy/Deep-Learning-Based-Anomaly-Detection#1]
the paper link in these 2 lines are same
https://github.com/bitzhangcy/Deep-Learning-Based-Anomaly-Detection/blob/main/README.md?plain=1#L163
https://github.com/bitzhangcy/Deep-Learning-Based-Anomaly-Detection/blob/main/README.md?plain=1#L167

the correct one for #L167 should be https://www.sciencedirect.com/science/article/abs/pii/S0925231221019482

**Comment by bitzhangcy** [comment]
Fixed the link on line #L167. Thanks for letting me know!
